version: '3.8'

services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - redis

    redis:
        image: redis:7
        container_name: laravel_redis
        ports:
            - "6379:6379"
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - laravel_network
        depends_on:
            - app

networks:
    laravel_network:
        driver: bridge
